# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namebytyping', '0003_auto_20160227_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='willing_to_speak',
            field=models.IntegerField(choices=[(1, 'willing_to_speak'), (0, 'unwilling_to_speak')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(0, 'female'), (1, 'male'), (-1, 'no_say')], default=0),
        ),
    ]
