# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('namebytyping', '0005_user_test_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='namebytyping.User'),
        ),
    ]
