# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-08 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namebytyping', '0006_time_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='extra_questions',
            field=models.CharField(default='-1', max_length=200),
        ),
    ]
